services:
  - type: web
    name: vplan-backend
    runtime: docker
    region: ohio
    plan: free
    dockerfilePath: ./Dockerfile.backend  # <--- Sin el # adelante
    envVars:
      - key: PORT
        value: 3001

  - type: web
    name: vplan-frontend
    runtime: docker
    region: ohio
    plan: free
    dockerfilePath: ./Dockerfile.frontend # <--- Sin el # adelante