services:
  - type: web
    name: vplan-backend
    env: docker
    region: ohio
    plan: free
    # Cambiamos esto:
    dockerfilePath: ./Dockerfile.backend 
    envVars:
      - key: PORT
        value: 3001

  - type: web
    name: vplan-frontend
    env: docker
    region: ohio
    plan: free
    # Y esto:
    dockerfilePath: ./Dockerfile.frontend